apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-role
  namespace: single-broker
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete"]