apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-rolebinding
  namespace: single-broker
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: kafka
roleRef:
  kind: Role
  name: strimzi-role
  apiGroup: rbac.authorization.k8s.io